# Generated by Django 5.1.5 on 2025-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_social_user_socialverificationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='social_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialverificationtoken',
            name='social_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
