# Generated by Django 5.1.5 on 2025-12-24 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', '무료'), ('basic', '베이직'), ('pro', '프로')], default='free', max_length=20, verbose_name='플랜 유형')),
                ('daily_note_limit', models.PositiveIntegerField(default=20, verbose_name='일일 노트 생성 제한')),
                ('daily_notes_created', models.PositiveIntegerField(default=0, verbose_name='오늘 생성한 노트 수')),
                ('daily_reset_date', models.DateField(auto_now_add=True, verbose_name='일일 카운터 리셋 날짜')),
                ('storage_limit_bytes', models.BigIntegerField(default=1073741824, verbose_name='스토리지 제한 (바이트)')),
                ('storage_used_bytes', models.BigIntegerField(default=0, verbose_name='사용 중인 스토리지 (바이트)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 쿼터',
                'verbose_name_plural': '사용자 쿼터',
            },
        ),
    ]
