# Generated by Django Migration
"""
데이터 마이그레이션: 기존 유저들의 UserQuota 생성 및 스토리지 사용량 계산
"""

from django.db import migrations
from django.db.models import Sum


def create_user_quotas(apps, schema_editor):
    """기존 유저들의 쿼터 생성 및 사용량 계산"""
    User = apps.get_model('accounts', 'User')
    UserQuota = apps.get_model('accounts', 'UserQuota')
    Note = apps.get_model('notes', 'Note')

    created_count = 0

    for user in User.objects.all():
        # 쿼터가 없으면 생성
        quota, created = UserQuota.objects.get_or_create(user=user)

        if created:
            created_count += 1

        # 현재 사용량 계산 (soft delete 포함 - all notes)
        # Note 모델의 all_objects 매니저를 사용할 수 없으므로 직접 쿼리
        total_storage = Note.objects.filter(
            user=user
        ).aggregate(total=Sum('file_size'))['total'] or 0

        quota.storage_used_bytes = total_storage
        quota.save(update_fields=['storage_used_bytes'])

    print(f"\n[create_user_quotas] Created {created_count} new quotas")


def reverse_create_user_quotas(apps, schema_editor):
    """역방향 마이그레이션: 모든 UserQuota 삭제"""
    UserQuota = apps.get_model('accounts', 'UserQuota')
    UserQuota.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_quota_and_file_size'),
        ('notes', '0016_populate_file_sizes'),  # file_size가 먼저 채워져야 함
    ]

    operations = [
        migrations.RunPython(
            create_user_quotas,
            reverse_create_user_quotas,
        ),
    ]
