# Generated by Django 5.1.5 on 2025-12-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_populate_master_account_data'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_by', models.CharField(choices=[('registration', '계정 생성 시'), ('auto_email', '이메일 자동 연결'), ('manual', '수동 연결')], default='registration', max_length=20, verbose_name='연결 방식')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='접근 횟수')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '소셜 계정 메타데이터',
                'verbose_name_plural': '소셜 계정 메타데이터',
            },
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='accountlinkingtoken',
            new_name='accounts_ac_token_84aba4_idx',
            old_name='accounts_ac_token_9d4e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='accountlinkingtoken',
            new_name='accounts_ac_user_id_c55f0a_idx',
            old_name='accounts_ac_user_id_b2f3d1_idx',
        ),
        migrations.RenameIndex(
            model_name='accountlinkingtoken',
            new_name='accounts_ac_expires_2498d0_idx',
            old_name='accounts_ac_expires_7c8f2a_idx',
        ),
        migrations.AlterField(
            model_name='accountlinkingtoken',
            name='link_type',
            field=models.CharField(choices=[('link_social', '소셜 계정 연결'), ('merge_accounts', '계정 병합'), ('set_password', '비밀번호 설정'), ('connect_init', '소셜 연결 초기화')], max_length=20, verbose_name='연결 유형'),
        ),
        migrations.AddField(
            model_name='socialaccountmetadata',
            name='social_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='socialaccount.socialaccount', verbose_name='소셜 계정'),
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
