# Generated by Django 5.1.5 on 2025-12-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_social_account_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_usable_password',
        ),
    ]
