# Generated by Django 5.1.5 on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_has_usable_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlinkingtoken',
            name='pending_email',
            field=models.EmailField(
                blank=True,
                null=True,
                max_length=254,
                verbose_name='인증 대기 이메일',
                help_text='소셜 로그인 시 사용자가 입력한 이메일 (인증 대기 중)'
            ),
        ),
        migrations.AddField(
            model_name='accountlinkingtoken',
            name='email_verification_token',
            field=models.UUIDField(
                null=True,
                blank=True,
                unique=True,
                verbose_name='이메일 인증 토큰'
            ),
        ),
        migrations.AddField(
            model_name='accountlinkingtoken',
            name='email_verification_sent_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name='인증 이메일 발송 시간'
            ),
        ),
        migrations.AddIndex(
            model_name='accountlinkingtoken',
            index=models.Index(
                fields=['email_verification_token'],
                name='accounts_ac_email_v_idx'
            ),
        ),
    ]
