# Generated by Django 5.2.16 on 2026-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_email_verification_to_accountlinkingtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountlinkingtoken',
            new_name='accounts_ac_email_v_5ca15b_idx',
            old_name='accounts_ac_email_v_idx',
        ),
        migrations.AlterField(
            model_name='accountlinkingtoken',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('email_verification', '이메일 인증 대기'), ('completed', '완료'), ('expired', '만료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': '이미 사용 중인 이메일 주소입니다.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
