"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys
import os
import ssl
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Add the 'apps' directory to the Python path
sys.path.append(str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY 환경 변수가 필요합니다")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    # Monitoring (must be first)
    'django_prometheus',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'apps.accounts',
    'apps.notes',
    'apps.support',
    'apps.notifications',

    # Third-party apps
    'storages',  # django-storages for S3/MinIO
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'corsheaders',

    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.naver',
    'allauth.socialaccount.providers.kakao',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',  # Prometheus (must be first)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 정적 파일 서빙 (DEBUG=False)
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',  # Prometheus (must be last)
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 전역 템플릿 디렉토리 추가
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 환경변수에서 데이터베이스 설정 읽기
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')

# verify-ca / verify-full 사용 시 필수. 미설정이면 OPTIONS에서 아예 생략한다
# (빈 문자열을 넘기면 libpq가 경로로 해석해 연결이 실패한다).
DB_SSL_ROOT_CERT = os.environ.get('DB_SSL_ROOT_CERT', '').strip()
if os.environ.get('DB_SSL_MODE', '').startswith('verify') and not DB_SSL_ROOT_CERT:
    raise ImproperlyConfigured(
        "DB_SSL_MODE가 verify-* 인데 DB_SSL_ROOT_CERT가 없습니다. "
        "사설 CA 인증서 경로를 지정하세요."
    )

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                # sslmode=verify-full이어야 중간자 공격을 막는다.
                # require는 암호화만 하고 서버 인증서를 검증하지 않으므로,
                # 공격자가 자기 인증서를 내밀어도 그대로 연결된다.
                'sslmode': os.environ.get('DB_SSL_MODE', 'disable'),
                # verify-ca / verify-full 사용 시 검증에 쓸 루트 CA 경로.
                # 사설 CA로 발급한 인증서라 시스템 신뢰 저장소에는 없다.
                **({'sslrootcert': DB_SSL_ROOT_CERT} if DB_SSL_ROOT_CERT else {}),
            },
        }
    }
else:
    # 기본값: SQLite (개발 환경)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploaded files)
# MinIO/S3 Storage Configuration
USE_S3 = os.environ.get('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # S3 (MinIO) Storage Settings - 외부 서버 사용
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'opennote-media')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', None)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'private'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # 1시간
    AWS_S3_USE_SSL = os.environ.get('AWS_S3_USE_SSL', 'True').lower() == 'true'
    # boto3의 verify는 boolean 또는 CA 번들 경로를 받는다.
    # MinIO 인증서를 사설 CA로 발급했으므로 시스템 신뢰 저장소에 없다.
    # 'True'로 두면 검증에 실패하므로 CA 경로를 넘겨야 한다.
    _s3_verify = os.environ.get('AWS_S3_VERIFY', 'True').strip()
    AWS_S3_VERIFY = (
        _s3_verify.lower() == 'true'
        if _s3_verify.lower() in ('true', 'false')
        else _s3_verify
    )

    # Storage Backend (Django 4.2+ STORAGES API)
    # MinIO 직접 연결 (내부 통신용)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # Media URL
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    # 기존 로컬 스토리지 유지
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # dj-rest-auth JWT 인증 (SIMPLE_JWT 대체)
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # 비인증 사용자: 시간당 100회
        'user': '1000/hour',  # 인증된 사용자: 시간당 1000회
        # 소셜 계정 관련 Rate Limiting
        'social_link': '10/hour',  # 소셜 계정 연결: 시간당 10회
        'social_unlink': '5/hour',  # 소셜 계정 해제: 시간당 5회
        'account_merge': '3/hour',  # 계정 병합: 시간당 3회
        'set_password': '5/hour',  # 비밀번호 설정: 시간당 5회
    },
    # 커스텀 예외 핸들러 (모든 DRF 예외 중앙 로깅)
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
    # 신뢰 프록시 단수 (클라이언트 → nginx → Django, 1단)
    # 미설정(None) 시 DRF는 X-Forwarded-For 헤더 "전체 문자열"을 스로틀 캐시 키로 쓴다.
    # 공격자가 헤더 앞부분만 바꾸면 매 요청이 새 키가 되어 AnonRateThrottle이
    # 아예 발동하지 않는다. 1로 지정하면 마지막 IP(신뢰 프록시가 붙인 실제 IP)만 사용한다.
    # 프록시 단수가 바뀌면 apps/common/client_ip.py와 함께 조정할 것.
    'NUM_PROXIES': 1,
}

# dj-rest-auth 설정 (JWT + 소셜 로그인 통합)
from datetime import timedelta

REST_AUTH = {
    # JWT 활성화
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access_token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh_token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SECURE': os.environ.get('JWT_AUTH_SECURE', 'False').lower() == 'true',
    'JWT_AUTH_SAMESITE': 'Lax',

    # Serializers
    'LOGIN_SERIALIZER': 'apps.accounts.serializers.CustomLoginSerializer',
    'REGISTER_SERIALIZER': 'apps.accounts.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'apps.accounts.serializers.UserProfileSerializer',
    'PASSWORD_RESET_URL_GENERATOR': 'config.settings.base.password_reset_url_generator',
}

# SIMPLE_JWT 설정 - 토큰 수명의 단일 출처 (dj-rest-auth는 이 값을 직접 참조)
# SIGNING_KEY를 JWT_SECRET 환경변수로 분리하여 sttEdit와 공유
SIMPLE_JWT = {
    'SIGNING_KEY': os.environ.get('JWT_SECRET', SECRET_KEY),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # 로테이션으로 교체된 구 refresh 토큰을 즉시 블랙리스트 처리한다.
    # 미설정(기본 False) 시 구 토큰이 만료(7일)까지 계속 유효해
    # 로테이션이 토큰 교체가 아니라 유효 토큰 증식이 된다.
    'BLACKLIST_AFTER_ROTATION': True,
}

# allauth settings
ACCOUNT_LOGIN_METHODS = ['username', 'email']
# By default, allauth will use the fields from ACCOUNT_LOGIN_METHODS 
# plus 'password' for the signup form. Explicitly setting 
# ACCOUNT_SIGNUP_FIELDS is often not needed if it's the same.
ACCOUNT_EMAIL_VERIFICATION = 'none' # For simplicity in development
ACCOUNT_ADAPTER = 'apps.accounts.adapter.CustomAccountAdapter'

# 신뢰 프록시 단수 (클라이언트 → nginx → Django, 1단)
# allauth는 이 값이 0(기본)이면 X-Forwarded-For를 아예 무시하고 REMOTE_ADDR을 쓴다.
# 그러면 모든 사용자가 nginx IP 하나로 묶여 IP 기준 제한(login 30/m/ip,
# signup 20/m/ip 등)이 전체 공유 버킷이 되어버린다. 1로 지정해 XFF의 마지막
# 값(신뢰 프록시가 붙인 실제 IP)만 사용한다.
# 프록시 단수가 바뀌면 apps/common/client_ip.py, REST_FRAMEWORK['NUM_PROXIES']와
# 함께 조정할 것.
ALLAUTH_TRUSTED_PROXY_COUNT = 1

# 회원가입 관련 설정
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False  # 이메일 인증 후 자동 로그인 비활성화
ACCOUNT_LOGIN_ON_PASSWORD_RESET = False      # 비밀번호 재설정 후 자동 로그인 비활성화


# CORS settings
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',') if origin.strip()
]
# OAuth 소셜 로그인에서 세션 쿠키 공유를 위해 credentials 허용
CORS_ALLOW_CREDENTIALS = True

# Email settings
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587')) if os.environ.get('EMAIL_PORT') else 587
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'OpenNote <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'OpenNote <noreply@opennote.dev>')

# Celery settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# amqps:// 사용 시 브로커 인증서 검증 설정.
# 사설 CA 발급분이라 시스템 신뢰 저장소에 없으므로 CA 경로를 명시해야 한다.
# CERT_REQUIRED가 아니면 인증서를 검증하지 않아 중간자 공격에 무방비다.
if CELERY_BROKER_URL.startswith('amqps://'):
    CELERY_BROKER_CA_CERT = os.environ.get('CELERY_BROKER_CA_CERT', '').strip()
    if not CELERY_BROKER_CA_CERT:
        raise ImproperlyConfigured(
            "CELERY_BROKER_URL이 amqps:// 인데 CELERY_BROKER_CA_CERT가 없습니다. "
            "사설 CA 인증서 경로를 지정하세요."
        )
    CELERY_BROKER_USE_SSL = {
        'ca_certs': CELERY_BROKER_CA_CERT,
        'cert_reqs': ssl.CERT_REQUIRED,
    }

# 직렬화
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 타임존
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_ENABLE_UTC = True

# Producer 설정 (웹서버)
CELERY_TASK_ALWAYS_EAGER = False  # 실제 큐 사용
CELERY_BROKER_POOL_LIMIT = 10
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# 결과 저장 설정
CELERY_RESULT_EXPIRES = 86400  # 24시간 후 결과 삭제
CELERY_RESULT_PERSISTENT = True

# Worker 설정 (GPU 워커용)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # GPU task는 한 번에 하나씩
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # 10개 task 후 재시작 (GPU 메모리 정리)
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_SEND_TASK_EVENTS = True  # Flower 모니터링용

# Celery는 기본값(True)이면 워커 기동 시 root 로거의 핸들러를 자기 것으로 교체한다.
# celery_workers/logging_config.py가 import 시점에 설치한 QueueHandler가 그때 제거되어
# 파일 로그가 전혀 남지 않았다(2026-02 이후 logs/*.log 미갱신). 실측:
#   기동 전 root 핸들러: ['StreamHandler', 'StreamHandler', 'QueueHandler']
#   기동 후 root 핸들러: ['StreamHandler']
# False로 두어 프로젝트의 로깅 설정을 유지한다.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Task 설정
CELERY_TASK_ACKS_LATE = True  # Task 완료 후 ack
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Worker 크래시 시 재큐잉
CELERY_TASK_TRACK_STARTED = True  # Task 시작 시점 추적
CELERY_TASK_TIME_LIMIT = 7200  # 2시간 hard limit (기본값)
CELERY_TASK_SOFT_TIME_LIMIT = 3600  # 1시간 soft limit (기본값)

# 재시도 설정
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 60초 후 재시도
CELERY_TASK_MAX_RETRIES = 3

# Celery Queue, Routes, Beat Schedule 설정 import
from config.settings.celery import (
    CELERY_TASK_QUEUES,
    CELERY_TASK_ROUTES,
    CELERY_BEAT_SCHEDULE
)

# Session Settings
SESSION_COOKIE_AGE = 21600  # 6시간 (초 단위: 6 * 60 * 60)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 브라우저를 닫아도 세션 유지
SESSION_SAVE_EVERY_REQUEST = True  # 요청이 있을 때마다 세션 갱신

# Session Security Settings (세션 보안 강화)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
SESSION_COOKIE_HTTPONLY = True  # JavaScript에서 세션 쿠키 접근 차단 (XSS 공격 방지)
# OAuth 소셜 로그인 지원을 위해 'Lax' 사용 (외부 사이트에서 리다이렉트 시 쿠키 전송 필요)
# 'Strict'는 외부 사이트(Kakao, Google 등)에서 리다이렉트 시 세션 쿠키가 전송되지 않아 state 검증 실패
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_NAME = 'opennote_sessionid'  # 기본 세션 쿠키명 변경 (보안상 우수)

# CSRF Protection Settings (CSRF 보안 강화)
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_HTTPONLY = True  # JavaScript에서 CSRF 쿠키 접근 차단
# OAuth 소셜 로그인과 API 호환성을 위해 'Lax' 사용
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'opennote_csrftoken'  # 기본 CSRF 쿠키명 변경
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
]

# Security Headers (보안 헤더 설정)
SECURE_CONTENT_TYPE_NOSNIFF = True  # MIME 스니핑 방지
X_FRAME_OPTIONS = 'DENY'  # 클릭재킹 방지 (iframe 차단)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 하위 도메인도 HTTPS 강제
SECURE_HSTS_PRELOAD = True  # 브라우저 HSTS 사전 로드 목록에 추가

# Prometheus /metrics 접근 제어 (sttEdit METRICS_ALLOWED_IPS와 동일 정책)
# 프록시 헤더를 신뢰하지 않고 REMOTE_ADDR만 본다 — 상세는 apps/common/metrics.py 참조.
# 스크레이퍼가 nginx·도커 브리지를 거치면 그 홉의 IP를 넣어야 한다.
METRICS_ALLOWED_IPS = os.environ.get('METRICS_ALLOWED_IPS', '127.0.0.1,::1')
METRICS_ENABLED = os.environ.get('METRICS_ENABLED', 'True').lower() == 'true'

# Cache Settings (브루트 포스 공격 방지용)
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'locmem')

if CACHE_BACKEND == 'redis':
    # Redis Standalone 캐시 (단일 노드)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'),
            'TIMEOUT': 300,  # 기본 5분 만료
            'KEY_PREFIX': 'opennote',
            'VERSION': 1,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }
elif CACHE_BACKEND == 'memcached':
    # Memcached 캐시 (대용량 처리)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': os.environ.get('MEMCACHED_URL', '127.0.0.1:11211'),
            'TIMEOUT': 300,  # 기본 5분 만료
            'KEY_PREFIX': 'opennote',
        }
    }
else:
    # 로컬 메모리 캐시 (개발 환경용)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,  # 기본 5분 만료
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        }
    }

# 브루트 포스 공격 방지 설정
LOGIN_ATTEMPT_LIMIT = int(os.environ.get('LOGIN_ATTEMPT_LIMIT', '5'))  # 로그인 최대 시도 횟수
LOGIN_LOCKOUT_DURATION = int(os.environ.get('LOGIN_LOCKOUT_DURATION', '300'))  # 로그인 잠금 시간 (초) - 5분
PASSWORD_RESET_ATTEMPT_LIMIT = int(os.environ.get('PASSWORD_RESET_ATTEMPT_LIMIT', '3'))  # 패스워드 리셋 최대 시도 횟수
PASSWORD_RESET_LOCKOUT_DURATION = int(os.environ.get('PASSWORD_RESET_LOCKOUT_DURATION', '600'))  # 패스워드 리셋 잠금 시간 (초) - 10분
REGISTRATION_ATTEMPT_LIMIT = int(os.environ.get('REGISTRATION_ATTEMPT_LIMIT', '5'))  # 회원가입 최대 시도 횟수
REGISTRATION_LOCKOUT_DURATION = int(os.environ.get('REGISTRATION_LOCKOUT_DURATION', '300'))  # 회원가입 잠금 시간 (초) - 5분
EMAIL_VERIFICATION_RESEND_LIMIT = int(os.environ.get('EMAIL_VERIFICATION_RESEND_LIMIT', '1'))  # 이메일 인증 재전송 최대 시도 횟수
EMAIL_VERIFICATION_RESEND_LOCKOUT_DURATION = int(os.environ.get('EMAIL_VERIFICATION_RESEND_LOCKOUT_DURATION', '600'))  # 이메일 인증 재전송 잠금 시간 (초) - 10분

# 프로필 이메일 변경 요청/재전송 제한
EMAIL_CHANGE_REQUEST_LIMIT = int(os.environ.get('EMAIL_CHANGE_REQUEST_LIMIT', '5'))  # 이메일 변경 요청 최대 시도 횟수
EMAIL_CHANGE_REQUEST_LOCKOUT_DURATION = int(os.environ.get('EMAIL_CHANGE_REQUEST_LOCKOUT_DURATION', '600'))  # 이메일 변경 요청 잠금 시간 (초) - 10분
EMAIL_CHANGE_RESEND_LIMIT = int(os.environ.get('EMAIL_CHANGE_RESEND_LIMIT', '5'))  # 이메일 변경 확인 메일 재전송 최대 시도 횟수
EMAIL_CHANGE_RESEND_LOCKOUT_DURATION = int(os.environ.get('EMAIL_CHANGE_RESEND_LOCKOUT_DURATION', '600'))  # 이메일 변경 재전송 잠금 시간 (초) - 10분

# dj-rest-auth 커스텀 설정
PASSWORD_RESET_USE_SITES_DOMAIN = False
OLD_PASSWORD_FIELD_ENABLED = True
LOGOUT_ON_PASSWORD_CHANGE = False


# 비밀번호 재설정 이메일에서 사용할 URL 설정
def password_reset_url_generator(request, user, temp_key):
    """
    비밀번호 재설정 이메일에서 사용할 URL 생성
    기존 프로젝트와 동일한 이메일 내용 사용
    """
    from django.utils.http import urlsafe_base64_encode
    from django.utils.encoding import force_bytes
    
    # 백엔드 URL로 먼저 리디렉션 (기존 프로젝트와 동일한 방식)
    backend_url = request.build_absolute_uri('/password-reset-confirm/')
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    return f"{backend_url}{uid}/{temp_key}/"


# allauth socialaccount 프로바이더 설정 (기존 SOCIAL_AUTH_* 대체)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [{
            'client_id': os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', ''),
            'secret': os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', ''),
        }],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'APPS': [{
            'client_id': os.environ.get('SOCIAL_AUTH_GITHUB_KEY', ''),
            'secret': os.environ.get('SOCIAL_AUTH_GITHUB_SECRET', ''),
        }],
        'SCOPE': ['user:email'],
    },
    'naver': {
        'APPS': [{
            'client_id': os.environ.get('SOCIAL_AUTH_NAVER_KEY', ''),
            'secret': os.environ.get('SOCIAL_AUTH_NAVER_SECRET', ''),
        }],
    },
    'kakao': {
        'APPS': [{
            'client_id': os.environ.get('SOCIAL_AUTH_KAKAO_KEY', ''),
            'secret': os.environ.get('SOCIAL_AUTH_KAKAO_SECRET', ''),
        }],
    },
}

# allauth socialaccount 설정
SOCIALACCOUNT_AUTO_SIGNUP = True  # 소셜 로그인 시 자동 회원가입
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # 이메일 기반 계정 연결
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # 동일 이메일 자동 연결
SOCIALACCOUNT_ADAPTER = 'apps.accounts.adapters.CustomSocialAccountAdapter'

# 소셜 로그인 콜백 URL 설정
GOOGLE_CALLBACK_URL = os.environ.get('GOOGLE_CALLBACK_URL', 'http://localhost:3000/auth/callback/google')
GITHUB_CALLBACK_URL = os.environ.get('GITHUB_CALLBACK_URL', 'http://localhost:3000/auth/callback/github')
NAVER_CALLBACK_URL = os.environ.get('NAVER_CALLBACK_URL', 'http://localhost:3000/auth/callback/naver')
KAKAO_CALLBACK_URL = os.environ.get('KAKAO_CALLBACK_URL', 'http://localhost:3000/auth/callback/kakao')

# 프론트엔드 URL 설정
FRONTEND_URL = os.environ.get('NEXT_PUBLIC_FRONTEND_URL', 'http://localhost:3000')

# Social Auth 로그인/로그아웃 URL
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = f'{FRONTEND_URL}/dashboard'  # 프론트엔드 대시보드로 리다이렉트
LOGOUT_URL = '/logout'
LOGOUT_REDIRECT_URL = f'{FRONTEND_URL}/'  # 프론트엔드 홈으로 리다이렉트


# =============================================================================
# Proxy Settings (nginx reverse proxy)
# =============================================================================

# Trust X-Forwarded-Proto header from nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust X-Forwarded-Host header
USE_X_FORWARDED_HOST = True


# =============================================================================
# Notification Settings
# =============================================================================

# 알림 보관 기간 (일) - 기본 90일
NOTIFICATION_RETENTION_DAYS = int(os.environ.get('NOTIFICATION_RETENTION_DAYS', '90'))

# 휴지통 보관 기간 (일) - 기본 30일
TRASH_RETENTION_DAYS = int(os.environ.get('TRASH_RETENTION_DAYS', '30'))

# 사이트 정보 (이메일 템플릿용)
SITE_NAME = os.environ.get('SITE_NAME', 'OpenNote')
SITE_URL = os.environ.get('SITE_URL', FRONTEND_URL)

# =============================================================================
# Logging Configuration (JSON structured logging for Loki)
# =============================================================================

# 로그 디렉토리 설정
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# 로그 보관 기간 (일)
LOG_RETENTION_DAYS = int(os.environ.get('LOG_RETENTION_DAYS', '7'))
ERROR_LOG_RETENTION_DAYS = int(os.environ.get('ERROR_LOG_RETENTION_DAYS', '30'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # JSON 포맷 (Loki 전송용) - SafeJsonFormatter 사용
        'json': {
            '()': 'config.logging_formatters.SafeJsonFormatter',
            'format': '%(timestamp)s %(level)s %(name)s %(message)s',
            'rename_fields': {
                'levelname': 'level',
                'asctime': 'timestamp',
            },
            'timestamp': True,
        },
        # 콘솔용 간단한 포맷
        'verbose': {
            'format': '{levelname} {asctime} [{name}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 콘솔 출력 (개발용)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # 전체 로그 파일 (JSON, 7일 보관)
        'file_json': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': LOG_RETENTION_DAYS,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
        # 에러 로그 파일 (JSON, 30일 보관)
        'error_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': ERROR_LOG_RETENTION_DAYS,
            'formatter': 'json',
            'level': 'ERROR',
            'encoding': 'utf-8',
        },
        # 보안 로그 파일 (JSON, 30일 보관)
        'security_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': ERROR_LOG_RETENTION_DAYS,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file_json'],
        'level': 'INFO',
    },
    'loggers': {
        # Django 요청/응답 로그
        'django.request': {
            'handlers': ['console', 'file_json', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django 보안 로그
        'django.security': {
            'handlers': ['console', 'file_json', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django DB 쿼리 (DEBUG 시에만)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 인증/계정 관련 로그
        'apps.accounts': {
            'handlers': ['console', 'file_json', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 노트 관련 로그
        'apps.notes': {
            'handlers': ['console', 'file_json'],
            'level': 'INFO',
            'propagate': False,
        },
        # 고객지원 관련 로그
        'apps.support': {
            'handlers': ['console', 'file_json'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery 태스크 로그
        'celery': {
            'handlers': ['console', 'file_json'],
            'level': 'INFO',
            'propagate': False,
        },
        # Gunicorn 로그
        'gunicorn.error': {
            'handlers': ['console', 'file_json', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.access': {
            'handlers': ['console', 'file_json'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
