# Generated by Django 5.1.5 on 2026-01-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='admin_reply',
            field=models.TextField(blank=True, verbose_name='관리자 답변'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='답변일'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='답변 관리자'),
        ),
    ]
