# Generated by Django 5.2.16 on 2026-08-05 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_add_admin_reply_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['user', 'created_at'], name='support_con_user_id_db1424_idx'),
        ),
    ]
