# Generated by Django 5.1.5 on 2025-08-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='processing_status',
            field=models.CharField(choices=[('processing', '음성 인식 중'), ('summarizing', '내용 요약 중'), ('completed', '처리 완료')], default='processing', max_length=20),
        ),
    ]
