# Generated by Django 5.1.5 on 2025-08-08 01:50

import apps.notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_preview_note_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(upload_to=apps.notes.models.note_audio_upload_path),
        ),
    ]
