# Generated by Django 5.1.5 on 2025-08-08 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='note',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='note',
            name='preview',
            field=models.TextField(blank=True, default='처리 대기 중...', null=True),
        ),
    ]
