# Generated by Django 5.1.5 on 2025-10-26 08:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_add_celery_processing_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processingtask',
            new_name='smartnote_p_status_52a4fb_idx',
            old_name='idx_task_status_created',
        ),
        migrations.RenameIndex(
            model_name='processingtask',
            new_name='smartnote_p_note_id_5c57b0_idx',
            old_name='idx_task_note_type',
        ),
        migrations.RenameIndex(
            model_name='processingtask',
            new_name='smartnote_p_celery__abfe60_idx',
            old_name='idx_task_celery_id',
        ),
        migrations.RenameIndex(
            model_name='workerheartbeat',
            new_name='smartnote_w_status_85ef21_idx',
            old_name='idx_worker_status_hb',
        ),
        migrations.RenameIndex(
            model_name='workerheartbeat',
            new_name='smartnote_w_worker__ab5827_idx',
            old_name='idx_worker_type_status',
        ),
        migrations.AlterField(
            model_name='summary',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
