# Generated by Django 5.1.5 on 2025-10-26 08:05

from django.db import migrations


def convert_keywords_to_array(apps, schema_editor):
    """기존 text 형식의 keywords를 array로 변환"""
    Summary = apps.get_model('notes', 'Summary')

    for summary in Summary.objects.all():
        if summary.keywords:
            # 기존 keywords가 string이면 쉼표로 분리하여 배열로 변환
            if isinstance(summary.keywords, str):
                keywords_list = [kw.strip() for kw in summary.keywords.split(',') if kw.strip()]
                summary.keywords = keywords_list
                summary.save(update_fields=['keywords'])


def reverse_keywords_to_text(apps, schema_editor):
    """롤백 시 array를 다시 text로 변환"""
    Summary = apps.get_model('notes', 'Summary')

    for summary in Summary.objects.all():
        if summary.keywords and isinstance(summary.keywords, list):
            # 배열을 쉼표로 구분된 문자열로 변환
            summary.keywords = ', '.join(summary.keywords)
            summary.save(update_fields=['keywords'])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_idx_task_status_created_smartnote_p_status_52a4fb_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_keywords_to_array, reverse_keywords_to_text),
    ]
