# Generated by Django 5.1.5 on 2025-10-26 08:06

from django.db import migrations


def add_idx_to_segments(apps, schema_editor):
    """기존 Note의 segment 데이터에 idx 필드 추가"""
    Note = apps.get_model('notes', 'Note')

    for note in Note.objects.all():
        if note.content and 'segments' in note.content:
            segments = note.content['segments']
            updated = False

            for idx, segment in enumerate(segments, start=1):
                # idx 필드가 없으면 추가
                if 'idx' not in segment:
                    segment['idx'] = idx
                    updated = True

            if updated:
                note.save(update_fields=['content'])


def remove_idx_from_segments(apps, schema_editor):
    """롤백 시 segment의 idx 필드 제거"""
    Note = apps.get_model('notes', 'Note')

    for note in Note.objects.all():
        if note.content and 'segments' in note.content:
            segments = note.content['segments']
            updated = False

            for segment in segments:
                if 'idx' in segment:
                    del segment['idx']
                    updated = True

            if updated:
                note.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_convert_keywords_to_array'),
    ]

    operations = [
        migrations.RunPython(add_idx_to_segments, remove_idx_from_segments),
    ]
