# Generated by Django 5.1.5 on 2025-10-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_unique_note_task_type_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSegment',
            fields=[
                ('segment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.FloatField(help_text='segment 시작 시간 (초)')),
                ('end', models.FloatField(help_text='segment 종료 시간 (초)')),
                ('idx', models.IntegerField(default=1, help_text='segment 순서')),
                ('speaker', models.CharField(help_text='발화자', max_length=255)),
                ('text', models.TextField(blank=True, default='', help_text='발화 문장')),
                ('words', models.JSONField(default=list, help_text='단어별 상세 정보 [{word, start, end, score, speaker}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(blank=True, help_text='수정일시', null=True)),
                ('stt_id', models.ForeignKey(db_column='stt_id', help_text='STT 참조 (Note 테이블)', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='notes.note')),
                ('updated_by', models.ForeignKey(blank=True, help_text='수정자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '노트 세그먼트',
                'verbose_name_plural': '노트 세그먼트',
                'db_table': 'notes_note_segment',
                'ordering': ['stt_id', 'idx'],
                'indexes': [models.Index(fields=['stt_id', 'idx'], name='notes_note__stt_id_72844a_idx'), models.Index(fields=['stt_id', 'speaker'], name='notes_note__stt_id_600a0e_idx')],
            },
        ),
    ]
