# Generated by Django 5.1.5 on 2025-10-28 13:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notesegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSegmentHistory',
            fields=[
                ('seg_hist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', help_text='변경 전 발화 문장')),
                ('words', models.JSONField(default=list, help_text='변경 전 단어별 상세 정보 [{word, start, end, score, speaker}, ...]')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='변경일시')),
                ('changed_by', models.ForeignKey(db_column='changed_by', help_text='변경자', on_delete=django.db.models.deletion.CASCADE, related_name='segment_changes', to=settings.AUTH_USER_MODEL)),
                ('segment_id', models.ForeignKey(db_column='segment_id', help_text='세그먼트 참조', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notes.notesegment')),
            ],
            options={
                'verbose_name': '노트 세그먼트 이력',
                'verbose_name_plural': '노트 세그먼트 이력',
                'db_table': 'notes_note_segment_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['segment_id', '-changed_at'], name='notes_note__segment_4770a4_idx'), models.Index(fields=['changed_by', '-changed_at'], name='notes_note__changed_f31be5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoteSummaryHistory',
            fields=[
                ('summary_hist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='변경 전 키워드 목록', size=None)),
                ('main_topic', models.TextField(blank=True, help_text='변경 전 주요 주제', null=True)),
                ('next_actions', models.TextField(blank=True, help_text='변경 전 다음 액션 아이템', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='변경일시')),
                ('changed_by', models.ForeignKey(db_column='changed_by', help_text='변경자', on_delete=django.db.models.deletion.CASCADE, related_name='summary_changes', to=settings.AUTH_USER_MODEL)),
                ('summary_id', models.ForeignKey(db_column='summary_id', help_text='요약 참조', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notes.summary')),
            ],
            options={
                'verbose_name': '노트 요약 이력',
                'verbose_name_plural': '노트 요약 이력',
                'db_table': 'notes_note_summary_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['summary_id', '-changed_at'], name='notes_note__summary_436527_idx'), models.Index(fields=['changed_by', '-changed_at'], name='notes_note__changed_765811_idx')],
            },
        ),
        migrations.CreateModel(
            name='SummarySectionHistory',
            fields=[
                ('sum_sec_hist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='섹션 제목', max_length=200)),
                ('content', models.TextField(help_text='섹션 내용')),
                ('order', models.IntegerField(default=0, help_text='정렬 순서')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='변경일시')),
                ('changed_by', models.ForeignKey(db_column='changed_by', help_text='변경자', on_delete=django.db.models.deletion.CASCADE, related_name='section_changes', to=settings.AUTH_USER_MODEL)),
                ('sum_sec_id', models.ForeignKey(db_column='sum_sec_id', help_text='요약 섹션 참조', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notes.summarysection')),
            ],
            options={
                'verbose_name': '요약 섹션 이력',
                'verbose_name_plural': '요약 섹션 이력',
                'db_table': 'notes_summarysection_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['sum_sec_id', '-changed_at'], name='notes_summa_sum_sec_7abaf4_idx'), models.Index(fields=['changed_by', '-changed_at'], name='notes_summa_changed_e8546a_idx')],
            },
        ),
    ]
