# Generated by Django 5.1.5 on 2025-12-20 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_notesegmenthistory_notesummaryhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='소프트 삭제 시점 (NULL이면 미삭제)', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='즐겨찾기 여부'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_favorite'], name='notes_note_user_fav_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'deleted_at'], name='notes_note_user_del_idx'),
        ),
    ]
