# Generated by Django 5.1.5 on 2025-12-20 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_add_favorites_and_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_description',
            field=models.TextField(blank=True, help_text='사용자가 입력한 노트 설명', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='user_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='사용자가 입력한 키워드 목록', size=None),
        ),
    ]
