# Generated by Django 5.1.5 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_add_user_description_and_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='오디오 파일 크기 (바이트)'),
        ),
    ]
