# Generated by Django Migration
"""
데이터 마이그레이션: 기존 노트들의 file_size 필드를 실제 파일 크기로 채움
"""

from django.db import migrations


def populate_file_sizes(apps, schema_editor):
    """기존 노트들의 파일 크기 계산"""
    Note = apps.get_model('notes', 'Note')

    updated_count = 0
    error_count = 0

    for note in Note.objects.filter(audio_file__isnull=False).exclude(audio_file=''):
        try:
            if note.audio_file:
                # 파일 시스템에서 실제 크기 조회
                note.file_size = note.audio_file.size
                note.save(update_fields=['file_size'])
                updated_count += 1
        except Exception as e:
            # 파일이 없거나 접근 불가한 경우 0으로 유지
            error_count += 1

    print(f"\n[populate_file_sizes] Updated {updated_count} notes, {error_count} errors")


def reverse_populate_file_sizes(apps, schema_editor):
    """역방향 마이그레이션: 모든 file_size를 0으로 리셋"""
    Note = apps.get_model('notes', 'Note')
    Note.objects.all().update(file_size=0)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_add_user_quota_and_file_size'),
    ]

    operations = [
        migrations.RunPython(
            populate_file_sizes,
            reverse_populate_file_sizes,
        ),
    ]
