# Generated by Django Migration
"""
마이그레이션: Note.speakers 필드 추가 및 기존 데이터 변환
- Note에 speakers JSONField 추가
- 기존 NoteSegment.speaker 값을 ID 형식(sp_0, sp_1 등)으로 변환
- Note.speakers에 스피커 메타데이터 저장
"""

from django.db import migrations, models, transaction


def migrate_speakers_forward(apps, schema_editor):
    """
    기존 스피커 데이터를 새 형식으로 변환
    - NoteSegment.speaker: "참석자1" → "sp_0"
    - Note.speakers: {"sp_0": {"name": "참석자1"}, ...}

    Note: 각 Note 단위로 트랜잭션 처리하여 부분 실패 방지
    """
    Note = apps.get_model('notes', 'Note')
    NoteSegment = apps.get_model('notes', 'NoteSegment')

    updated_notes = 0
    updated_segments = 0

    for note in Note.objects.all():
        segments = NoteSegment.objects.filter(stt_id=note).order_by('idx')

        if not segments.exists():
            continue

        # 고유 스피커 추출 (등장 순서 유지)
        unique_speakers = []
        has_legacy_speakers = False
        for seg in segments:
            if seg.speaker:
                # 이미 sp_ 형식이면 스킵 (이미 마이그레이션된 데이터)
                if seg.speaker.startswith('sp_'):
                    continue
                has_legacy_speakers = True
                if seg.speaker not in unique_speakers:
                    unique_speakers.append(seg.speaker)

        # 이미 마이그레이션된 경우 스킵
        if not has_legacy_speakers:
            continue

        # 스피커 매핑 생성
        speakers = {}
        speaker_map = {}
        for idx, name in enumerate(unique_speakers):
            sp_id = f"sp_{idx}"
            speakers[sp_id] = {"name": name}
            speaker_map[name] = sp_id

        # 각 Note 단위로 원자적 트랜잭션 처리
        with transaction.atomic():
            # Note.speakers 업데이트
            note.speakers = speakers
            note.save(update_fields=['speakers'])
            updated_notes += 1

            # 각 세그먼트의 speaker 값을 ID로 변환
            for seg in segments:
                if seg.speaker in speaker_map:
                    seg.speaker = speaker_map[seg.speaker]
                    seg.save(update_fields=['speaker'])
                    updated_segments += 1

    print(f"\n[migrate_speakers] Updated {updated_notes} notes, {updated_segments} segments")


def migrate_speakers_reverse(apps, schema_editor):
    """
    역방향 마이그레이션: ID를 다시 이름으로 변환
    """
    Note = apps.get_model('notes', 'Note')
    NoteSegment = apps.get_model('notes', 'NoteSegment')

    for note in Note.objects.exclude(speakers={}).exclude(speakers__isnull=True):
        speakers = note.speakers or {}

        # 각 세그먼트의 speaker ID를 이름으로 복원
        for seg in NoteSegment.objects.filter(stt_id=note):
            if seg.speaker and seg.speaker.startswith('sp_'):
                speaker_info = speakers.get(seg.speaker, {})
                if speaker_info.get('name'):
                    seg.speaker = speaker_info['name']
                    seg.save(update_fields=['speaker'])

        # Note.speakers 초기화
        note.speakers = {}
        note.save(update_fields=['speakers'])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_populate_file_sizes'),
    ]

    operations = [
        # 1. speakers 필드 추가
        migrations.AddField(
            model_name='note',
            name='speakers',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='스피커 정보: {"sp_0": {"name": "참석자1"}, "sp_1": {"name": "참석자2"}, ...}'
            ),
        ),
        # 2. 기존 데이터 변환
        migrations.RunPython(
            migrate_speakers_forward,
            migrate_speakers_reverse,
        ),
    ]
