# Generated by Django 5.1.5 on 2026-01-27 10:02

import apps.notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_add_speakers_and_migrate_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='시스템이 자동 생성한 샘플 노트 여부'),
        ),
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=apps.notes.models.note_audio_upload_path),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sample', True)), fields=('user',), name='unique_sample_note_per_user'),
        ),
    ]
