# Generated by Django 5.1.5 on 2026-03-24 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_fix_sample_note_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'processing_status'], name='notes_note_user_status_idx'),
        ),
    ]
