# Generated by Django 5.1.5 on 2026-01-23 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='알림 ID')),
                ('notification_type', models.CharField(choices=[('inquiry_reply', '문의 답변'), ('system', '시스템 공지')], max_length=50, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='참조 ID')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='이동 URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='참조 타입')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'), models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'), models.Index(fields=['created_at'], name='notif_created_idx')],
            },
        ),
    ]
